INSERT INTO scientific_sources (
    source_key, title, authors, published_year, url, training_focus,
    evidence_level, summary, population_studied, research_objective,
    stimulus_analyzed, expected_benefits, limitations, risks,
    contraindications, confidence_level, last_reviewed_on, related_rules
) VALUES (
    'post-competition-recovery-2019',
    'Optimizing recovery to support multi-evening cycling competition performance',
    'Normand A. Richard; Michael S. Koehle',
    2019,
    'https://pubmed.ncbi.nlm.nih.gov/30589619/',
    'post_competition_recovery',
    'systematic_review',
    'Revisão sobre recuperação em contexto de competição de ciclismo; informa priorizar recuperação e atividade leve, sem dose universal.',
    'Ciclistas e atletas de endurance em contexto de competição; consultar os critérios da revisão original.',
    'Revisar estratégias para recuperar desempenho entre esforços competitivos próximos.',
    'Recuperação passiva, sono, nutrição, hidratação e atividade leve após esforço intenso.',
    'Apoia reduzir estímulos exigentes e considerar atividade leve durante a recuperação.',
    'Revisão de contexto competitivo específico; não valida duração, RPE ou janela fixa para todos os atletas.',
    'A carga inadequada após competição pode prolongar fadiga; sinais individuais devem prevalecer.',
    'Não usar para substituir avaliação profissional diante de dor, sintomas ou restrição médica.',
    'moderate',
    DATE '2026-09-14',
    ARRAY['rules-v1', 'post_event_recovery']
)
ON CONFLICT (source_key) DO UPDATE SET
    title = EXCLUDED.title,
    authors = EXCLUDED.authors,
    published_year = EXCLUDED.published_year,
    url = EXCLUDED.url,
    training_focus = EXCLUDED.training_focus,
    evidence_level = EXCLUDED.evidence_level,
    summary = EXCLUDED.summary,
    population_studied = EXCLUDED.population_studied,
    research_objective = EXCLUDED.research_objective,
    stimulus_analyzed = EXCLUDED.stimulus_analyzed,
    expected_benefits = EXCLUDED.expected_benefits,
    limitations = EXCLUDED.limitations,
    risks = EXCLUDED.risks,
    contraindications = EXCLUDED.contraindications,
    confidence_level = EXCLUDED.confidence_level,
    last_reviewed_on = EXCLUDED.last_reviewed_on,
    related_rules = EXCLUDED.related_rules;

INSERT INTO scientific_sources (
    source_key, title, authors, published_year, url, training_focus,
    evidence_level, summary, population_studied, research_objective,
    stimulus_analyzed, expected_benefits, limitations, risks,
    contraindications, confidence_level, last_reviewed_on, related_rules
) VALUES (
    'recovery-umbrella-2024',
    'Effectiveness of Recovery Strategies After Training and Competition in Endurance Athletes: An Umbrella Review',
    'Shuting Li; Matthias Kempe; Michel Brink; Koen Lemmink',
    2024,
    'https://pubmed.ncbi.nlm.nih.gov/38753045/',
    'post_competition_recovery',
    'systematic_review',
    'Umbrella review de 22 revisões e 1100 atletas; não encontrou uma estratégia de recuperação consistentemente eficaz para todos os atletas de endurance.',
    'Atletas de endurance, incluindo ciclistas, em estudos de recuperação após treino ou competição.',
    'Avaliar a consistência da eficácia de estratégias de recuperação em atletas de endurance.',
    'Estratégias de recuperação pós-esforço e seus efeitos no desempenho e na fadiga.',
    'Justifica cautela e redução de carga, mas não escolhe uma estratégia universal nem uma dose de treino.',
    'Populações, estratégias e desfechos heterogêneos; a revisão não define janela ou duração de pedal leve.',
    'Interpretar a redução de carga como proteção operacional, não como tratamento de fadiga ou lesão.',
    'Não usar para substituir avaliação profissional diante de dor, sintomas ou restrição médica.',
    'moderate',
    DATE '2026-09-14',
    ARRAY['rules-v1', 'post_event_recovery']
)
ON CONFLICT (source_key) DO UPDATE SET
    title = EXCLUDED.title,
    authors = EXCLUDED.authors,
    published_year = EXCLUDED.published_year,
    url = EXCLUDED.url,
    training_focus = EXCLUDED.training_focus,
    evidence_level = EXCLUDED.evidence_level,
    summary = EXCLUDED.summary,
    population_studied = EXCLUDED.population_studied,
    research_objective = EXCLUDED.research_objective,
    stimulus_analyzed = EXCLUDED.stimulus_analyzed,
    expected_benefits = EXCLUDED.expected_benefits,
    limitations = EXCLUDED.limitations,
    risks = EXCLUDED.risks,
    contraindications = EXCLUDED.contraindications,
    confidence_level = EXCLUDED.confidence_level,
    last_reviewed_on = EXCLUDED.last_reviewed_on,
    related_rules = EXCLUDED.related_rules;
