// Package i18n translates the text the API returns. The engine, the database and
// the error codes stay in Portuguese; when the request asks for English
// (Accept-Language), the response is translated on the way out using a catalog
// keyed by the exact Portuguese text. Text without an entry (the athlete's own
// notes, names and plans generated by older engine versions) is left as is.
package i18n

import (
	"context"
	"fmt"
	"regexp"
	"sort"
	"strings"
)

type Language string

const (
	Portuguese Language = "pt"
	English    Language = "en"
)

// FromAcceptLanguage reads the first tag of the header. Only English switches
// the language; anything else, including no header, keeps Portuguese.
func FromAcceptLanguage(header string) Language {
	first := strings.TrimSpace(strings.SplitN(header, ",", 2)[0])
	first = strings.ToLower(strings.SplitN(first, ";", 2)[0])
	if first == "en" || strings.HasPrefix(first, "en-") {
		return English
	}
	return Portuguese
}

type contextKey struct{}

func WithLanguage(ctx context.Context, language Language) context.Context {
	return context.WithValue(ctx, contextKey{}, language)
}

func FromContext(ctx context.Context) Language {
	if language, ok := ctx.Value(contextKey{}).(Language); ok {
		return language
	}
	return Portuguese
}

type pattern struct {
	matcher *regexp.Regexp
	// verbs holds the verb of each capture group, in order (s or d).
	verbs   []byte
	english string
}

var verb = regexp.MustCompile(`%(\.\d+)?[sdf]`)

var patterns = compilePatterns(englishPatterns)

func compilePatterns(source map[string]string) []pattern {
	keys := make([]string, 0, len(source))
	for key := range source {
		keys = append(keys, key)
	}
	// Longer keys first, so a more specific format wins over a generic one.
	sort.Slice(keys, func(i, j int) bool { return len(keys[i]) > len(keys[j]) })
	compiled := make([]pattern, 0, len(keys))
	for _, key := range keys {
		var expression strings.Builder
		var verbs []byte
		last := 0
		for _, location := range verb.FindAllStringIndex(key, -1) {
			expression.WriteString(regexp.QuoteMeta(key[last:location[0]]))
			switch kind := key[location[1]-1]; kind {
			case 's':
				expression.WriteString(`(.+?)`)
				verbs = append(verbs, 's')
			default:
				expression.WriteString(`(-?\d+(?:[.,]\d+)?)`)
				verbs = append(verbs, 'd')
			}
			last = location[1]
		}
		expression.WriteString(regexp.QuoteMeta(key[last:]))
		compiled = append(compiled, pattern{
			matcher: regexp.MustCompile(`^` + expression.String() + `$`),
			verbs:   verbs,
			english: source[key],
		})
	}
	return compiled
}

// T returns text in the requested language. Portuguese, and any text without a
// translation, come back unchanged.
func T(language Language, text string) string {
	if language != English || text == "" {
		return text
	}
	if translated, ok := translate(text); ok {
		return translated
	}
	return text
}

// Has reports whether text has an English translation (used by tests that keep
// the catalog in step with the engine).
func Has(text string) bool {
	_, ok := translate(text)
	return ok
}

func translate(text string) (string, bool) {
	if translated, ok := exact(text); ok {
		return translated, true
	}
	return segments(text)
}

// exact covers a catalog entry, a formatted entry, or an entry followed by a
// final period that the engine adds when it reuses a phrase as a sentence.
func exact(text string) (string, bool) {
	if translated, ok := english[text]; ok {
		return translated, true
	}
	if translated, ok := formatted(text); ok {
		return translated, true
	}
	if base, found := strings.CutSuffix(text, "."); found {
		if translated, ok := english[base]; ok {
			return translated + ".", true
		}
	}
	return "", false
}

func formatted(text string) (string, bool) {
	for _, candidate := range patterns {
		groups := candidate.matcher.FindStringSubmatch(text)
		if groups == nil {
			continue
		}
		args := make([]any, 0, len(candidate.verbs))
		ok := true
		for index, kind := range candidate.verbs {
			value := groups[index+1]
			if kind == 's' {
				// A text argument must itself be translatable; otherwise a
				// generic format would also match the athlete's own text.
				translated, found := exact(value)
				if !found {
					ok = false
					break
				}
				value = translated
			} else {
				value = strings.ReplaceAll(value, ",", ".")
			}
			args = append(args, value)
		}
		if ok {
			return fmt.Sprintf(candidate.english, args...), true
		}
	}
	return "", false
}

// segments handles text the engine builds by appending sentences that each
// have a translation (a summary plus a pre-race note, for example). Every part
// must translate, or the text is left as it is.
func segments(text string) (string, bool) {
	for end := len(text) - 1; end > 0; end-- {
		if text[end] != ' ' || (text[end-1] != '.' && text[end-1] != ';') {
			continue
		}
		head, ok := exact(text[:end])
		if !ok {
			continue
		}
		if tail, ok := translate(strings.TrimSpace(text[end:])); ok {
			return head + " " + tail, true
		}
	}
	return "", false
}

// Value walks a JSON-like value (maps, slices, strings) and translates every
// string that has an entry. Keys are never translated.
func Value(language Language, value any) any {
	if language != English {
		return value
	}
	switch typed := value.(type) {
	case string:
		return T(language, typed)
	case map[string]any:
		for key, item := range typed {
			typed[key] = Value(language, item)
		}
		return typed
	case []any:
		for index, item := range typed {
			typed[index] = Value(language, item)
		}
		return typed
	default:
		return value
	}
}
