import { LEGAL_CONTACT_EMAIL, type LegalDocument } from './legal';

// Tradução para o inglês da Política de Privacidade e dos Termos de Uso. A
// versão em português é a que vale juridicamente (o aviso aparece no topo da
// página em inglês). As seções têm os mesmos ids e a mesma ordem do português, e
// um teste confere isso: ao mudar um texto em legal.ts, mude também aqui.

export const PRIVACY_POLICY_EN: LegalDocument = {
  kicker: 'PRIVACY',
  title: 'Privacy Policy',
  intro:
    'This policy explains what data Cadência keeps about you, what each item is used for, who it is shared with and how you control it. It follows the Brazilian General Data Protection Law (LGPD, Law 13,709/2018).',
  sections: [
    {
      id: 'responsavel',
      title: 'Who is responsible for your data',
      paragraphs: [
        'Cadência is developed and operated by Saulo Rangel, who decides how the data is processed (the controller, under the LGPD).',
        `For any request or question about your data, write to ${LEGAL_CONTACT_EMAIL}.`,
      ],
    },
    {
      id: 'dados',
      title: 'What data we collect',
      paragraphs: ['We only collect what you enter or generate while using the app:'],
      items: [
        'Account: name, email, password (stored only as an irreversible hash, never as plain text) and the dates the account was created and the email was confirmed.',
        'Profile: date of birth, sex, height, weight, waist, body fat percentage, activity level and cycling experience.',
        'Health and limitations, which are sensitive personal data: injuries, pain, medical restrictions, recent surgeries and conditions that affect exercise, when you report them.',
        'Cycling context: routine, equipment, goals, weekly availability and, if you enter them, FTP and power data.',
        'Training: generated plans, completed sessions, perceived effort (RPE), fatigue, pain, feedback, assessments and recovery check-ins (sleep, stress and fatigue).',
        'Activities imported from the .fit, .gpx or .tcx files you upload: date and time, duration, distance, elevation and average heart rate, power and cadence. The route (GPS coordinates) is read to calculate these numbers and is not stored.',
        'Messages you send through the in-app feedback form.',
        'Record of acceptance: the date and version of the Terms of Use and Privacy Policy you accepted.',
        'Technical data: a session cookie and server and network access logs, such as IP address and time, used for security.',
      ],
    },
    {
      id: 'finalidades',
      title: 'What we use it for, and on what legal basis',
      items: [
        'Building and adjusting your workouts, recording your progress and showing the results: performance of the service you requested (LGPD, art. 7, V).',
        'Processing your health data and limitations to make workouts safer: your specific consent, given when you accept these documents and when you enter that data (art. 11, I). You can withdraw it at any time by deleting the information from your profile or deleting your account.',
        'Keeping the service secure, limiting improper access attempts and investigating abuse: legitimate interest (art. 7, IX).',
        'Meeting legal obligations, when there are any.',
      ],
      after: [
        'We do not use your data for advertising, we do not sell it and we do not build commercial profiles.',
        'Workouts are generated by planning rules defined by the product, based on scientific studies cited in the app, and not by a final machine decision about you: you decide whether to do, cancel or log as missed each session. If you want a review of a plan that was generated automatically, ask through the contact above.',
        'Cadência does not provide medical diagnosis or treatment.',
      ],
    },
    {
      id: 'compartilhamento',
      title: 'Who we share it with',
      paragraphs: [
        'We use service providers (processors) that handle data on our behalf and only for the agreed service:',
      ],
      items: [
        'Hosting: a cloud virtual server, where the app and the database live, and Cloudflare, which carries traffic between your device and the server.',
        'Transactional email (Resend): receives your email address and the text of the email confirmation and password reset messages.',
        'Backup: encrypted copies of the database, in external storage at Oracle.',
        "AI workout explanation: when you ask for a session's explanation, a language model, accessed through a service on Cloudflare, receives only the workout name, goal, duration, target effort and the planning rules applied. It does not receive your name, email, health data, history or imported activities.",
      ],
      after: [
        'Cloudflare and Resend may process data outside Brazil. In those cases, the transfer is necessary to provide the service (LGPD, art. 33, IX).',
        'We do not share your data with advertisers or other users. We only disclose it to authorities when the law requires it.',
      ],
    },
    {
      id: 'retencao',
      title: 'How long we keep it',
      items: [
        'Your data is kept while the account exists.',
        'When you delete your account in Settings, we erase all of your data from the database immediately, without anyone stepping in.',
        'Backups made before the deletion remain for a limited time and are then discarded: on the server, for up to 14 days, and in the encrypted external copy, kept in Oracle storage, for up to 60 days. After those periods, your data no longer exists in any copy.',
        'Technical access logs are kept for as long as needed for security.',
      ],
    },
    {
      id: 'direitos',
      title: 'Your rights',
      paragraphs: ['You can, at any time and at no cost (LGPD, art. 18):'],
      items: [
        `Confirm that we process your data and access it. In Settings, the "Download my spreadsheet" button gives you your account data, completed workouts and imported activities. For a full copy, including health data and limitations, write to ${LEGAL_CONTACT_EMAIL}.`,
        'Correct incomplete or outdated data: in Profile, and in the workout logs that allow correction.',
        'Take your data to another service: the spreadsheet opens in any spreadsheet program and can be converted to other formats.',
        'Delete your data: in Settings, "Delete account".',
        'Know who we share data with, as described in the section above.',
        'Withdraw consent and ask for a review of automated decisions.',
      ],
      after: [
        `For anything you cannot do yourself, write to ${LEGAL_CONTACT_EMAIL}. We reply within 15 days.`,
        'You can also file a complaint with the Brazilian National Data Protection Authority (ANPD), at gov.br/anpd.',
      ],
    },
    {
      id: 'seguranca',
      title: 'How we protect your data',
      items: [
        'Encrypted connection (HTTPS) between your device and the server.',
        'Passwords stored with a bcrypt hash; the session cookie is HttpOnly, secure and protected against cross-site sending.',
        'Each account can only access its own data; you can end sessions open on other devices.',
        'Limits on attempts at sign-in, sign-up and password reset.',
        'Encrypted backups.',
      ],
      after: [
        'No system is completely secure. If an incident happens that may cause you relevant risk or harm, we will notify you and the ANPD, as the law requires (art. 48).',
      ],
    },
    {
      id: 'cookies',
      title: 'Cookies and storage on your device',
      paragraphs: [
        'We use one essential cookie, which keeps you signed in, and we only store interface preferences in the browser, such as whether the app was installed. We do not use advertising cookies or third-party analytics tools.',
      ],
    },
    {
      id: 'menores',
      title: 'Children and teenagers',
      paragraphs: [
        'Cadência is intended for people aged 18 or over. If we identify an account belonging to a minor, we will delete the data.',
      ],
    },
    {
      id: 'mudancas',
      title: 'Changes to this policy',
      paragraphs: [
        'When we change something that affects your data, such as a new provider or a new integration, we update this page and the date at the top, and we notify you in the app before the change takes effect. A new integration that requires new data only starts with your consent.',
      ],
    },
  ],
};

export const TERMS_OF_USE_EN: LegalDocument = {
  kicker: 'TERMS',
  title: 'Terms of Use',
  intro:
    'These terms apply to the use of Cadência, a cycling training planning app. By creating an account, you state that you have read and agree to them and to the Privacy Policy.',
  sections: [
    {
      id: 'elegibilidade',
      title: 'Who can use it',
      paragraphs: [
        'Cadência is intended for people aged 18 or over. The account is personal and you must provide true information.',
      ],
    },
    {
      id: 'servico',
      title: 'What Cadência is, and what it is not',
      paragraphs: [
        'Cadência suggests cycling workouts based on your profile, routine and records. It is not a medical, physiotherapy or nutrition service, does not diagnose and does not replace guidance from health or exercise professionals.',
        'Before starting or increasing your training load, especially if you have an illness, injury, medical restriction or recent surgery, see a professional. Stop the workout if you feel pain, dizziness, shortness of breath or any discomfort. You decide whether to do each workout and how, and you are responsible for that decision.',
      ],
    },
    {
      id: 'conta',
      title: 'Your account',
      items: [
        'Keep your password safe and do not share it. You are responsible for what happens in your account.',
        'Let us know if you suspect improper access. In Settings, you can change your password and end sessions open on other devices.',
        'You can delete your account at any time, in Settings, and your data is erased.',
      ],
    },
    {
      id: 'uso-adequado',
      title: 'Acceptable use',
      paragraphs: ['You may not:'],
      items: [
        "try to access other accounts' data or get around the app's security;",
        'overload the service or use automated means that harm other users;',
        'upload files or text that are illegal, offensive or not yours.',
      ],
      after: ['We may suspend accounts that break these rules.'],
    },
    {
      id: 'seus-dados',
      title: 'Your data and content',
      paragraphs: [
        'The data and files you upload remain yours. You authorize us to process them only to operate Cadência for you, as described in the Privacy Policy.',
      ],
    },
    {
      id: 'ia-e-ciencia',
      title: 'AI explanations and scientific basis',
      paragraphs: [
        "Workouts come from planning rules. The explanations written by artificial intelligence summarize those rules and may contain inaccuracies: trust the workout and the rules shown, not an AI's text.",
        "The studies cited in the app give general support to training principles. The app's thresholds, time frames and percentages are product choices, and the app says so when that is the case. Studies of population groups do not guarantee the same result for you.",
      ],
    },
    {
      id: 'disponibilidade',
      title: 'Availability and changes',
      paragraphs: [
        'Cadência is evolving and is offered as is. It may be unavailable for maintenance or because of a failure, and features may change or be removed. We will do our best to give notice before changes that affect your data.',
      ],
    },
    {
      id: 'responsabilidade',
      title: 'Liability',
      paragraphs: [
        'To the extent permitted by law, Cadência does not guarantee performance, health or body composition results, and is not liable for injuries, damage or losses resulting from the training you chose to do. Nothing here removes rights the law grants you, including those under the Brazilian Consumer Protection Code.',
        'Integrations with third-party services, when they exist, are offered by those third parties. They make no warranties and take no responsibility for Cadência.',
      ],
    },
    {
      id: 'lei',
      title: 'Governing law',
      paragraphs: [
        'The laws of Brazil apply. If you are a consumer, the competent court is the one where you live.',
      ],
    },
    {
      id: 'mudancas',
      title: 'Changes and contact',
      paragraphs: [
        `We may update these terms; the date at the top shows the version in force, and we notify you in the app when the change is relevant. Questions: ${LEGAL_CONTACT_EMAIL}.`,
      ],
    },
  ],
};
